---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-enketo
  labels:
    app: {{ include "kobo.labels.app" . }}
    component: enketo
    chart: {{ include "kobo.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  key: {{ randAlphaNum 10 | b64enc | quote }}
  encryption-key: {{ randAlphaNum 10 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-enketo-create-config-script
  labels:
    app: {{ include "kobo.labels.app" . }}
    component: enketo
    chart: {{ include "kobo.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  "create_config.py": |-
    {{ .Files.Get "files/enketo/create_config.py" | b64enc }}
---
