apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobo.fullname" . }}-kpi
  labels:
    app: {{ include "kobo.labels.app" . }}
    component: kpi
    chart: {{ include "kobo.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.kpi.service.type }}
  selector:
    app: {{ include "kobo.labels.app" . }}
    component: kpi
    release: {{ .Release.Name }}
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: 8000
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
