apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobo.fullname" . }}-enketo
  labels:
    app: {{ include "kobo.labels.app" . }}
    component: enketo
    chart: {{ include "kobo.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.kobocat.service.type }}
  selector:
    app: {{ include "kobo.labels.app" . }}
    component: enketo
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
