repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "migrations|snapshots"
        stages: [commit]
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: "docker-compose run backend python manage.py test --noinput"
        language: python
        always_run: true
        pass_filenames: false
        stages: [push]
