repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--config=backend/pyproject.toml]
        exclude: "migrations|snapshots"
        stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=backend/.flake8]
        additional_dependencies: [flake8-bugbear==22.9.23]
        stages: [ commit ]
  # mypy precomit hook
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        verbose: true
        args: [--config-file=backend/pyproject.toml, --follow-imports=skip]
        pass_filenames: true
        stages: [commit]
        additional_dependencies: [
          types-requests==2.28.11.2,
          types-redis==4.3.21.2,
          types-python-dateutil==2.8.19.2,
          types-pytz==2022.4.0.0,
          django-webtest==1.9.10,
          factory-boy==2.12.0,
          faker==13.12.1,
          freezegun==0.3.14,
          ipdb==0.13.9,
          isort==5.10.1,
          parameterized==0.8.1,
          requests-mock==1.9.3,
          responses==0.21.0,
          snapshottest==1.0.0a0,
          unittest-xml-reporting==3.2.0,
          watchdog==2.1.8,
          wasmer==1.1.0,
          parso==0.8.3,
          argh==0.26.2,
          flake8==4.0.1,
          flake8-formatter-junit-xml==0.0.6,
          flake8-bugbear==22.9.23,
          mypy==0.982,
          types-requests==2.28.11.2,
          types-redis==4.3.21.2,
          types-python-dateutil==2.8.19.2,
          types-pytz==2022.4.0.0,
          djangorestframework-stubs==1.7.0,
          graphene-stubs==0.15,
          django-stubs==1.12.0
        ]
