repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        args: [ '--version' ]
        #        args: [ '--src', 'src/','--check-only' ]
        entry: isort
        language: python
        types: [ python ]
        additional_dependencies: [ isort ]
      - id: black
        name: black
        args: [ '--check' ]
        entry: black
        language: python
        types: [ python ]
        require_serial: true
        additional_dependencies: [ black ]
#repos:
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
#        stages: [commit]
#  - repo: https://github.com/ambv/black
#    rev: 23.9.1
#    hooks:
#      - id: black
#        args: [--config=backend/pyproject.toml]
#        exclude: "migrations|snapshots"
#        stages: [commit]
#  - repo: https://github.com/PyCQA/flake8
#    rev: 6.1.0
#    hooks:
#      - id: flake8
#        args: [--config=backend/.flake8]
#        additional_dependencies: [flake8-bugbear==22.12.6]
#        stages: [ commit ]
#        exclude: /deployment/|/migrations/
#  # mypy precommit hook
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.982
#    hooks:
#      - id: mypy
#        verbose: true
#        args: [--config-file=backend/pyproject.toml, --follow-imports=skip]
#        pass_filenames: true
#        stages: [commit]
#        additional_dependencies: [
#          types-requests==2.28.11.15,
#          types-redis==4.5.1.4,
#          types-python-dateutil==2.8.19.10,
#          types-pytz==2022.7.1.2,
#          djangorestframework-stubs==1.9.1,
#          graphene-stubs==0.15,
#          django-stubs==1.15.0,
#          django-stubs-ext==0.7.0,
#          openpyxl-stubs==0.1.25
#        ]
#        exclude: /deployment/|/migrations/
