repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--config=backend/pyproject.toml]
        exclude: "migrations|snapshots"
        stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=backend/.flake8]
        additional_dependencies: [flake8-bugbear==22.9.23]
        stages: [ commit ]
  # mypy precomit hook
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--config-file=backend/pyproject.toml, --follow-imports=skip]
        pass_filenames: true
        stages: [commit]
        additional_dependencies: [
          types-requests==2.28.11.2,
          types-redis==4.3.21.2,
          types-python-dateutil==2.8.19.2,
          types-pytz==2022.4.0.0,
        ]
