version: "1.0"
stages:
  - clone
  - build
  - push
steps:
  main_clone:
    type: git-clone
    description: "Cloning main repository..."
    repo: unicef/hct-mis
    revision: ${{CF_BRANCH}}
    stage: clone

  build_images:
    type: parallel
    stage: build
    steps:
      build_backend:
        type: build
        image_name: unicef/hct-mis-backend
        working_directory: ${{main_clone}}/backend
        dockerfile: Dockerfile
        tag: ${{CF_BRANCH}}
        build_arguments:
          - env=${{ENV}}
          - GIT_VERSION=${{CF_REVISION}}

      build_frontend:
        type: build
        image_name: unicef/hct-mis-frontend
        working_directory: ${{main_clone}}/frontend
        dockerfile: Dockerfile
        tag: ${{CF_BRANCH}}

      build_proxy:
        type: build
        image_name: unicef/hct-mis-proxy
        working_directory: ${{main_clone}}/proxy
        dockerfile: Dockerfile
        tag: ${{CF_BRANCH}}

  approval_for_push:
    type: pending-approval
    title: "Should we run push"
    when:
      branch:
        only:
          - develop
    stage: push
  parallel_push:
    type: parallel
    steps:
      # annotate_build:
      #   title: "Annotating Build"
      #   image: ${{build_images}}
      #   working_directory: IMAGE_WORK_DIR
      #   commands:
      #     - echo "Annotating Build..."
      #   on_success:
      #     metadata:
      #       set:
      #         - ${{build_images.imageId}}:
      #           - CF_QUALITY: true
      #   on_error:
      #     metadata:
      #       set:
      #         - ${{build_images.imageId}}:
      #           - CF_QUALITY: false
      push_backend:
        title: "Pushing backend image to cfcr"
        type: push
        registry: cfcr
        candidate: ${{build_backend}}
        tags:
          - ${{CF_BRANCH_TAG_NORMALIZED}}
          - ${{CF_REVISION}}
      push_frontend:
        title: "Pushing frontend image to cfcr"
        type: push
        registry: cfcr
        candidate: ${{build_frontend}}
        tags:
          - ${{CF_BRANCH_TAG_NORMALIZED}}
          - ${{CF_REVISION}}
      push_proxy:
        title: "Pushing proxy image to cfcr"
        type: push
        registry: cfcr
        candidate: ${{build_proxy}}
        tags:
          - ${{CF_BRANCH_TAG_NORMALIZED}}
          - ${{CF_REVISION}}
    stage: push