version: '3.7'

volumes:
  backend-data:
  backend-web-app:
  db:
  data_es:

services:
  selenium:
    stdin_open: true
    tty: true
    image: unicef/hct-mis-backend-dev
    shm_size: 2gb
    environment:
      - REDIS_INSTANCE=redis:6379
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=secretkey
      - ENV=dev
      - DEBUG=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CACHE_LOCATION=redis://redis:6379/1
      - DATABASE_URL=postgis://postgres:postgres@db:5432/postgres
      - DATABASE_URL_HUB_MIS=postgis://postgres:postgres@db:5432/mis_datahub
      - DATABASE_URL_HUB_CA=postgis://postgres:postgres@db:5432/ca_datahub
      - DATABASE_URL_HUB_ERP=postgis://postgres:postgres@db:5432/erp_datahub
      - DATABASE_URL_HUB_REGISTRATION=postgis://postgres:postgres@db:5432/rdi_datahub
      - USE_DUMMY_EXCHANGE_RATES=yes
      - CELERY_TASK_ALWAYS_EAGER=true
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - DISPLAY=host.docker.internal:0
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./backend/report/screenshot/:/code/screenshot/
      - ./backend/report/:/code/report/
      - backend-data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - backend-data-selenium:/data
      - ./backend/selenium_tests:/code/selenium_tests
      - type: volume
        source: backend-web-app-selenium
        target: /code/hct_mis_api/apps/web/static
        volume:
          nocopy: false
    command: |
      sh -c "
        waitforit -host=db -port=5432 -timeout=30 &&
        pytest -svvv -m "not mapping" selenium_tests --html=./report/report.html
      "
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
      init_fe:
        condition: service_completed_successfully
      selenium-hub:
        condition: service_started

  init_fe:
    image: unicef/hct-mis-backend-dist
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: dist
    volumes:
      - backend-web-app-selenium:/tmp
    command: |
      sh -c "
        cp -r ./hct_mis_api/apps/web/static/* /tmp/
      "
    restart: "no"


  redis:
    restart: always
    image: redis:4.0.11-alpine3.8
    expose:
      - "6379"

  db:
    image: kartoza/postgis:14-3
    volumes:
      - db-selenium:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=unicef_hct_mis_cashassist,rdi_datahub,mis_datahub,erp_datahub,ca_datahub
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_SSL_MODE=off
    ports:
      - "5433:5432"

  elasticsearch:
    image: unicef/hct-elasticsearch
    container_name: elasticsearch
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es-selenium:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"