version: '3.7'
services:
  selenium:
    stdin_open: true
    entrypoint: entrypoint.sh
    image: unicef/hct-mis-backend
    env_file:
      - .env
    environment:
      - REDIS_INSTANCE=redis:6379
      - PYTHONUNBUFFERED=1
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: selenium
    volumes:
      - ./backend/screenshot/:/code/screenshot/
      - backend-data:/data
      - ipython_data_local:/root/.ipython
    command: |
      sh -c "
        waitforit -host=db -port=5432 -timeout=30 &&
        pytest -sv selenium_tests
      "
    depends_on:
      - db
      - redis
      - elasticsearch
