[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | snapshots
)/
'''
# TODO: remove migrations exclude rule once it won't create much conflicts between feature branches and develop
[tool.isort]
py_version = 39
profile = "black"
default_section = "THIRDPARTY"
known_first_party = [
    "account",
    "core",
    "grievance",
    "household",
    "id_management",
    "intervention",
    "payment",
    "program",
    "targeting.apps.TargetingConfig",
    "utils",
    "registration_datahub",
    "mptt",
    "django_extensions",
    "registration_data",
    "cash_assist_datahub",
    "mis_datahub",
    "erp_datahub",
    "sanction_list",
    "accountability",
]
known_django = "django"
sections = ["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
include_trailing_comma = true
skip = ["migrations", "snapshots", "venv"]

[tool.mypy]
python_version = 3.11
show_error_codes = true
exclude = [
  "migrations",
  "venv",
  "snapshots",
]

strict = true

ignore_missing_imports = true # TODO
follow_imports = "skip"

# TODO: remove one, fix errors, repeat
disable_error_code = [
  "var-annotated", # this enforces Django Model fields to have type annotations
  "attr-defined",
  "misc", # cannot subclass DjangoObjectType
  "union-attr",
  "type-arg", # this misses type parameters for graphene.ObjectType
  "no-any-return", # this enforces adding return None for function that returns None
]

[tool.django-stubs]
django_settings_module = "hct_mis_api.settings"


[tool.poetry]
name = "HCT MIS Backend"
version = "2.2.0"
description = "HCT MIS is UNICEF's humanitarian cash transfer platform."
authors = ["Tivix"]

[tool.poetry.dependencies]
python = "3.11.*"

defusedxml = "0.7.0rc1"

Django = "~3.2.15"
elasticsearch ="~7.13"
graphene-django = "~2.14.0"
openpyxl = "~3.0.10"

Jinja2 = "^3.1.3"
MarkupSafe = "^2.1.1"
PyJWT = "^2.4.0"
PyYAML = "^6.0"
black = "^23"
celery = {extras = ["redis"], version = "^5.2.7"}
coreapi = "^2.3.3"
django-admin-cursor-paginator = "^0.1.3"
django-admin-extra-buttons = "^1.5.4"
django-admin-sync = "^0.7"
django-adminactions = "^2.1"
django-adminfilters = "2.4.2"
django-advanced-filters = "^2.0.0"
django-auditlog = "^2.1.1"
django-celery-beat = "^2.3.0"
django-celery-results = "^2.3.1"
django-concurrency = "^2.4"
django-constance = { version = "^2.9", extras = ["redis"] }
django-cors-headers = "^3.13.0"
django-countries = "^7.3.2"
django-csp = "^3.7"
django-elasticsearch-dsl = "^7.2.2"
django-environ = "^0.10.0"
django-extensions = "^3.1.5"
django-filter = "^22"
django-flags = "^5.0.12"
django-front-door = "^0.10"
django-fsm = "^2.8.0"
django-hijack = "^3.2.1"
django-import-export = "^2.8.0"  # mayor
django-import-export-celery = "^1.2"
django-jsoneditor = "^0.2.2"
django-markdownify = "^0.9.2"
django-model-utils = "^4.2.0"
django-mptt = "^0.14"
django-multiselectfield = "^0.1.12"
django-phonenumber-field = "^7"
django-redis = "^5.2.0"
django-reversion = "^5.0.2"
django-silk = "^5.0.1"
django-smart-admin = "^2"
django-sql-explorer = {extras = ["xls"], version = "^3"}
django-storages = { version = "^1.12.3", extras = ["azure"] }
django-strategy-field = "^3.0"
django-sysinfo = "^2.6.0"
django_compressor = "^4.0"
django-querysetsequence = "^0.16"
djangorestframework = "^3.13.1"
drf-jwt = "^1.19.2"
drf-spectacular = { version = "^0.27", extras = ["sidecar"] }
elasticsearch-dsl ="^7.0.0"
factory-boy = "^3"
gevent = "^23.9"  # error installing
graphene-file-upload = "^1.3.0"
gunicorn = "^20.1.0"
ipython = "^8.4.0"
jedi = "^0.18.1"
jmespath = "^1.0.1"
natural-keys = "^2.0.0"
openpyxl_image_loader = "^1.0.5"
phonenumbers = "^8.12.49"
pillow = "^10.2.0"
pre_commit = "^3.1.1"
prompt-toolkit = "^3.0.29"
psycopg2 = "^2.9.3"
ptyprocess = "^0.7.0"
pycountry = "^22.3"
pygments = "^2.12.0"
pytesseract = "^0.3.9"
pytz = "^2022.1"
single-source = "^0.3.0"
social-auth-app-django = "^5.0.0"
social-auth-core = "^4.2.0"
sorl-thumbnail = "^12.8.0"
swapper = "^1.3.0"
tblib = "^1.7.0"
unicef-power-query = "^0.4"
update = "^0.0.1"
urllib3 = "^1.26.9"
xlrd = "^1.2"  # update to 2 breaks
weasyprint = "^59.0"
pytest-cov = "^4.1.0"
coverage = "^7.3.2"
tomli = "^2.0.1"
sentry-sdk = "1.40.5"
django-debug-toolbar = "^4.3.0"
django-graphiql-debug-toolbar = "^0.2.0"

[tool.poetry.group.dev.dependencies]
mypy = "0.982"
django-stubs = "~1.12.0"  # more pypi
django-stubs-ext = "^0.7.0"  # more pypi
djangorestframework-stubs = "~1.7.0"  # more pypi

argh = "^0.28"
django-webtest = "^1.9.10"
faker = "^17"
flake8 = "^6"
flake8-absolute-import = "^1.0.0.1"
flake8-bugbear = "^22.9.23"
flake8-formatter-junit-xml = "^0.0.6"
freezegun = "^0.3"
graphene-stubs = "^0.15"
ipdb = "^0.13.9"
isort = "^5.10.1"
openpyxl-stubs = "^0.1.24"
parameterized = "^0.8.1"
parso = "^0.8.3"
pytest = "^7.4.4"
pytest-django = "^4.5.2"
pytest-echo = "^1.7.1"
pytest-html ="^4.1.1"
selenium = "4.16.0"
requests-mock = "^1.9.3"
responses = "^0.22"
snapshottest = "^1.0.0a0"
types-freezegun = "^1.1.10"
types-requests = "^2.28.11.2"
types-python-dateutil = "^2.8.19.2"
types-pytz = "^2022.4.0.0"
types-redis = "^4.3.21.2"
unittest-xml-reporting = "^3.2.0"
watchdog = "^2.1.8"
wasmer = "^1.1.0"
types-selenium = "^3.141.9"
pytest-rerunfailures = "^13.0"
pytest-randomly = "^3.15.0"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.5.0"
pytest-repeat = "^0.9.3"
flaky = "^3.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

