{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hope.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hope.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{.Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
    - host: {{.Values.ingress.host }}
      http:
        paths:
        - path: /api/
          backend:
            serviceName: {{ $fullName }}-backend
            servicePort: {{ .Values.backend.service.port }}
        - path: /
          backend:
            serviceName: {{ $fullName }}-frontend
            servicePort: {{ .Values.frontend.service.port }}
{{- end }}
