apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hope.fullname" . }}-backend
  labels:
    {{- include "hope.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "hope.postgresql.password" . | nindent 2 }}
  {{- include "hope.registrationdatahubpostgresql.password" . | nindent 2 }}
  {{- include "hope.cashassistdatahubpostgresql.password" . | nindent 2 }}
{{- range $key, $value :=  .Values.backend.secret }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
