apiVersion: v1
kind: Secret
metadata:
  name: hope-airflow-extra
  labels:
    {{- include "hope.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "hope.postgresql.password" . | nindent 2 }}
  {{- include "hope.postgresql.airflow.password" . | nindent 2 }}
  {{- include "hope.registrationdatahubpostgresql.password" . | nindent 2 }}
  {{- include "hope.cashassistdatahubpostgresql.password" . | nindent 2 }}
{{- range $key, $value :=  .Values.backend.secret }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
---
# Hack for Airflow Helm Chart
apiVersion: v1
kind: Secret
metadata:
  name: hope-redis
  labels:
    {{- include "hope.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ "hack-not-used" | b64enc | quote }}
