apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hope.fullname" . }}-frontend
  labels:
    {{- include "hope.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value :=  .Values.frontend.secret }}
  {{ if eq $value "" }}
  {{ else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
