version: "3.7"

volumes:
  backend-data-selenium:
  backend-web-app-selenium:
  db-selenium-data:
  data_es-selenium:

services:
  redis:
    restart: always
    image: redis:4.0.11-alpine3.8
    ports:
      - 6379:6379

  db_selenium:
    image: kartoza/postgis:14-3
    volumes:
      - db-selenium-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=unicef_hct_mis_cashassist,rdi_datahub,mis_datahub,erp_datahub,ca_datahub
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_SSL_MODE=off
    ports:
      - 5432:5432

  elasticsearch:
    image: unicef/hct-elasticsearch
    container_name: elasticsearch
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es-selenium:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
