version: '3.7'
x-django-envs: &django_envs
  environment:
    - ENV=dev
    - SECRET_KEY=31283012-38dasda
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - DATABASE_URL=postgis://postgres:postgres@db:5432/postgres
    - DATABASE_URL_HUB_MIS=postgis://postgres:postgres@db:5432/mis_datahub
    - DATABASE_URL_HUB_CA=postgis://postgres:postgres@db:5432/ca_datahub
    - DATABASE_URL_HUB_ERP=postgis://postgres:postgres@db:5432/erp_datahub
    - DATABASE_URL_HUB_REGISTRATION=postgis://postgres:postgres@db:5432/rdi_datahub
    - POSTGRES_SSL_MODE=off
    - EMAIL_HOST=TBD
    - EMAIL_HOST_USER=TBD
    - EMAIL_HOST_PASSWORD=TBD
    - KOBO_KF_URL=https://kobo.humanitarianresponse.info
    - KOBO_KC_URL=https://kobo.humanitarianresponse.info
    - KOBO_MASTER_API_TOKEN=token
    - EXCHANGE_RATES_API_KEY=token
    - REDIS_INSTANCE=redis:6379
    - PYTHONUNBUFFERED=1

services:
  redis:
    restart: unless-stopped
    image: redis:4.0.11-alpine3.8

  backend:
    <<: *django_envs
    image: ${backend_image}
    command: "test"
    volumes:
      - ../backend:/code/
      - ../backend/test-coverage:/code/backend/test-coverage
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: kartoza/postgis:14-3
    volumes:
      - ../postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=unicef_hct_mis_cashassist,rdi_datahub,mis_datahub,erp_datahub,ca_datahub
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_SSL_MODE=off
    ports:
      - "5433:5432"

  celery_worker:
    <<: *django_envs
    image: ${backend_image}
    restart: unless-stopped
    command: "celery -A hct_mis_api.apps.core.celery worker -E -l info"
    depends_on:
      - backend
      - db
      - redis
      - elasticsearch

  elasticsearch:
    <<: *django_envs
    image: unicef/hct-elasticsearch
    build:
      context: ../development_tools/elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
