global:
  env: staging
  storageClass: default

backend:
  image: #from-pipeline
  replicaCount: 1
  config:
    POSTGRES_SSL: true
  secret:
    AZURE_CLIENT_ID: #secret-variables: AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET: #secret-variables: AZURE_CLIENT_SECRET
    AZURE_TENANT_KEY: #secret-variables: AZURE_TENANT_KEY
    STORAGE_AZURE_ACCOUNT_NAME: saunihopestg
    STORAGE_AZURE_ACCOUNT_KEY: #secret-variables: STORAGE_AZURE_ACCOUNT_KEY
    SECRET_KEY: #secret-variables: SECRET_KEY
    SENTRY_DSN: "https://19e762af45a845c2b131fc5170c5be6c@excubo.unicef.io/14"
    EMAIL_HOST: extmail01.unicef.org
    EMAIL_USE_TLS: "false"
    EXCHANGE_RATES_API_KEY: #secret-variables: EXCHANGE_RATES_API_KEY
    ROOT_ACCESS_TOKEN: #secret-variables: ROOT_ACCESS_TOKEN

frontend:
  image: #from-pipeline

celery:
  image: #from-pipeline
  replicaCount: 1

celeryflower:
  secret:
    FLOWER_BASIC_AUTH: #secret-variables: FLOWER_BASIC_AUTH

ingress:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: cert-ictd-hope-dev-aks-unitst-tls
  host: stg-hope.unitst.org


postgresql:
  enabled: false
  externalDatabase:
    host: pgsql-10-reserved-hctmis-tstuat.postgres.database.azure.com
    user: hctapptstusr@pgsql-10-reserved-hctmis-tstuat
    password: #secret-variables: POSTGRES_PASSWORD
    db: tst_hctmis_appdb
registrationdatahubpostgresql:
  enabled: false
  externalDatabase:
    host: pgsql-10-reserved-hctmis-tstuat.postgres.database.azure.com
    user: reghubtstusr@pgsql-10-reserved-hctmis-tstuat
    password: #secret-variables: REGISTRATION_DATAHUB_POSTGRES_PASSWORD
    db: tst_registration_datahubdb
cashassistdatahubpostgresql:
  enabled: false
  externalDatabase:
    host: pgsql-10-reserved-hctmis-tstuat.postgres.database.azure.com 
    user: cashubtstusr@pgsql-10-reserved-hctmis-tstuat
    password: #secret-variables: CASH_ASSIST_DATAHUB_POSTGRES_PASSWORD
    db: tst_cashassist_datahubdb
