trigger: none
pr:
  - master
  - develop
  - feature/*
resources:
  - repo: self

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Docker.backend.filePath: "**/backend/Dockerfile"
  Docker.frontend.filePath: "**/frontend/Dockerfile"
  Docker.cypress.filePath: "**/cypress/Dockerfile"
  Docker.registryConnection: "ICTD-HOPE-DEV-ACR"
  tag: '$(Build.SourceBranchName)'
  Docker.backend.repository: "hope-backend"
  Docker.frontend.repository: "hope-frontend"
  Docker.url: "uniappsakshopedev.azurecr.io"
  Kubernetes.serviceConnection: "ICTD-HOPE-DEV-uni-apps-aks-dev-ictd-hope-dev-1593457625386"
  Kubernetes.namespace: "ictd-hope-dev"

stages:
  - stage: test_frontend
    displayName: Test-Frontend
    jobs:
      - job: frontend_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[FRONTEND TEST]"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: $(Build.SourcesDirectory)/frontend/yarn.lock
              path: $(Build.SourcesDirectory)/frontend/node_modules
            displayName: Cache Yarn packages
          - script: yarn
            displayName: "Yarn Install"
            workingDirectory: 'frontend'
          - script: yarn test --watchAll=false
            workingDirectory: 'frontend'
            displayName: "Test"

  - stage: check_format
    dependsOn: []
    displayName: Check BE format
    jobs:
      - job: check_format
        pool:
          vmImage: ubuntu-latest
        displayName: "[CHECK FORMAT]"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.9"
            displayName: "Use Python 3.9"
          - script: pip install black==22.8.0 isort==5.10.1
          # remember to update this if you change the version of black/isort in pyproject.toml
            displayName: "Install tools"
          - script: black --check .
            workingDirectory: 'backend'
            displayName: "Check format"
          - script: isort --check-only .
            workingDirectory: 'backend'
            displayName: "Check imports order"


  - stage: build_and_push
    dependsOn: check_format
    displayName: BUILD and PUSH
    jobs:
      - job: build_push_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "[Build]"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registryConnection)'
              command: 'login'
          - script: "docker pull $(Docker.url)/$(Docker.backend.repository):$(System.PullRequest.PullRequestId)-latest"
            displayName: Pull latest for layer caching for this branch
            continueOnError: true # for first build, no cache
          - script: "docker pull $(Docker.url)/$(Docker.backend.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              arguments: "--cache-from=$(Docker.url)/$(Docker.backend.repository):$(System.PullRequest.PullRequestId)-latest 
                          --cache-from=$(Docker.url)/$(Docker.backend.repository):latest"
              dockerfile: $(Docker.backend.filePath)
              repository: $(Docker.backend.repository)
              containerRegistry: $(Docker.registryConnection)
              tags: |
                $(Build.BuildId)
                dev-latest
                $(System.PullRequest.PullRequestId)-latest
          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              dockerfile: $(Docker.backend.filePath)
              repository: $(Docker.backend.repository)
              containerRegistry: $(Docker.registryConnection)
              tags: |
                $(Build.BuildId)
                dev-latest
                $(System.PullRequest.PullRequestId)-latest

  - stage: build_and_push_frontend
    dependsOn: test_frontend
    displayName: BUILD and PUSH Frontend
    jobs:
      - job: build_and_push_frontend
        pool:
          vmImage: ubuntu-latest
        displayName: "[Build_Frontend]"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registryConnection)'
              command: 'login'
          - task: Cache@2
            displayName: Cache task
            inputs:
              key: 'docker | "$(Agent.OS)" | cache'
              path: $(Pipeline.Workspace)/docker
              cacheHitVar: CACHE_RESTORED
          - script: |
              docker load -i $(Pipeline.Workspace)/docker/cache.tar
            displayName: Docker restore
            condition: and(not(canceled()), eq(variables.CACHE_RESTORED, 'true'))
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              dockerfile: $(Docker.frontend.filePath)
              repository: $(Docker.frontend.repository)
              containerRegistry: $(Docker.registryConnection)
              tags: |
                $(tag)
          - script: |
              mkdir -p $(Pipeline.Workspace)/docker
              docker save -o $(Pipeline.Workspace)/docker/cache.tar $(Docker.url)/$(Docker.frontend.repository):$(tag)
            displayName: Docker save
            condition: and(not(canceled()), or(failed(), ne(variables.CACHE_RESTORED, 'true')))

  - stage: build_and_push_cypress
    dependsOn: test_frontend
    displayName: BUILD and PUSH cypress
    jobs:
      - job: build_and_push_cypress
        pool:
          vmImage: ubuntu-latest
        displayName: "[Build_Cypress]"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registryConnection)'
              command: 'login'
          - script: "docker pull $(Docker.url)/$(Docker.frontend.repository):cypress-latest"
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              arguments: "--cache-from=$(Docker.url)/$(Docker.frontend.repository):cypress-latest"
              dockerfile: $(Docker.cypress.filePath)
              repository: $(Docker.frontend.repository)
              containerRegistry: $(Docker.registryConnection)
              tags: |
                cypress-latest
          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              dockerfile: $(Docker.cypress.filePath)
              repository: $(Docker.frontend.repository)
              containerRegistry: $(Docker.registryConnection)
              tags: |
                cypress-latest

  # - stage: lint_backend
  #   dependsOn: build_and_push
  #   displayName: Lint-Backend
  #   jobs:
  #     - job: django_lint
  #       pool:
  #         vmImage: ubuntu-latest
  #       displayName: "[DJANGO LINT]"
  #       variables:
  #         backend_image: $(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)
  #       steps:
  #         - task: Docker@2
  #           displayName: "[ACR] Login"
  #           inputs:
  #             command: login
  #             containerRegistry: $(Docker.registry)

  #         - task: DockerCompose@0
  #           displayName: "Run tests"
  #           inputs:
  #             containerregistrytype: 'Azure Container Registry'
  #             azureContainerRegistry: $(Docker.registry)
  #             dockerComposeFile: '**/docker-compose.tst.yml'
  #             action: 'Run a Docker Compose command'
  #             dockerComposeCommand: 'run --no-deps backend lint'
  #             dockerComposeFileArgs: |
  #              backend_image=$(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)

  #         - task: PublishTestResults@2
  #           displayName: "Publish lint result"
  #           condition: always()
  #           inputs:
  #             testResultsFormat: 'JUnit'
  #             testResultsFiles: '*.xml'
  #             searchFolder: 'backend/lint-results/'
  #             mergeTestResults: true
  #             failTaskOnFailedTests: true
  #             testRunTitle: 'Lint results'

  # - stage: mypy_backend
  #   dependsOn: build_and_push
  #   displayName: Mypy-Backend
  #   jobs:
  #     - job: django_mypy
  #       pool:
  #         vmImage: ubuntu-latest
  #       displayName: "[DJANGO MYPY]"
  #       variables:
  #         backend_image: $(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)
  #       steps:
  #         - task: Docker@2
  #           displayName: "[ACR] Login"
  #           inputs:
  #             command: login
  #             containerRegistry: $(Docker.registry)

  #         - task: DockerCompose@0
  #           displayName: "Run tests"
  #           inputs:
  #             containerregistrytype: 'Azure Container Registry'
  #             azureContainerRegistry: $(Docker.registry)
  #             dockerComposeFile: '**/docker-compose.tst.yml'
  #             action: 'Run a Docker Compose command'
  #             dockerComposeCommand: 'run --no-deps backend mypy'
  #             dockerComposeFileArgs: |
  #              backend_image=$(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)

  #         - task: PublishTestResults@2
  #           displayName: "Publish mypy result"
  #           condition: always()
  #           inputs:
  #             testResultsFormat: 'JUnit'
  #             testResultsFiles: '*.xml'
  #             searchFolder: 'backend/mypy-results/'
  #             mergeTestResults: true
  #             failTaskOnFailedTests: true
  #             testRunTitle: 'Mypy results'

  # - stage: test_backend
  #   dependsOn: [lint_backend, mypy_backend]
  #   displayName: Test-Backend
  #   jobs:
  #     - job: django_tests
  #       pool:
  #         vmImage: ubuntu-latest
  #       displayName: "[DJANGO TEST]"
  #       variables:
  #         backend_image: $(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)
  #       steps:
  #         - task: Docker@2
  #           displayName: "[ACR] Login"
  #           inputs:
  #             command: login
  #             containerRegistry: $(Docker.registry)
  #         - task: DockerCompose@0
  #           displayName: "Run tests"
  #           inputs:
  #             containerregistrytype: 'Azure Container Registry'
  #             azureContainerRegistry: $(Docker.registry)
  #             dockerComposeFile: '**/docker-compose.tst.yml'
  #             action: 'Run a Docker Compose command'
  #             dockerComposeCommand: 'run backend test'
  #             dockerComposeFileArgs: |
  #              backend_image=$(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)

  #         - task: PublishTestResults@2
  #           displayName: "Publish Test Result"
  #           condition: always()
  #           inputs:
  #             testResultsFormat: 'JUnit'
  #             testResultsFiles: '*.xml'
  #             searchFolder: 'backend/test-results/'
  #             mergeTestResults: true
  #             failTaskOnFailedTests: true
  #             testRunTitle: 'TEST Results'

  - stage: e2e_tests
    # dependsOn: [test_backend, test_frontend]
    dependsOn: [build_and_push, build_and_push_frontend, test_frontend, build_and_push_cypress]
    displayName: E2E-Tests
    jobs:
      - job: cypress_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[CYPRESS TEST]"
        steps:
          - task: Docker@2
            displayName: "[ACR] Login"
            inputs:
              command: login
              containerRegistry: $(Docker.registryConnection)
          - task: DockerCompose@0
            displayName: "Run tests"
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureContainerRegistry: $(Docker.registryConnection)
              dockerComposeFile: '**/docker-compose.cy.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'run cypress test'
              dockerComposeFileArgs: |
               backend_image=$(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)
               frontend_image=$(Docker.url)/$(Docker.frontend.repository):$(tag)
               cypress_image=$(Docker.url)/$(Docker.frontend.repository):cypress-latest
          - script: ls -la
            condition: always()
            workingDirectory: 'cypress'
          - script: ls -la cypress
            condition: always()
            workingDirectory: 'cypress'
          - task: PublishTestResults@2
            displayName: "Publish Test Result"
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '*.xml'
              searchFolder: 'cypress/cypress/results/'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'TEST Results'
