trigger: none
pr:
  - master
  - develop
resources:
  - repo: self

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Docker.backend.filePath: "**/backend/Dockerfile"
  Docker.frontend.filePath: "**/frontend/Dockerfile"
  Docker.registry: "ICTD-HOPE-DEV-ACR"
  Docker.backend.repository: "hope-backend"
  Docker.frontend.repository: "hope-frontend"
  Docker.url: "uniappsakshopedev.azurecr.io"
  Kubernetes.serviceConnection: "ICTD-HOPE-DEV-uni-apps-aks-dev-ictd-hope-dev-1593457625386"
  Kubernetes.namespace: "ictd-hope-dev"

stages:
  - stage: test_frontend
    displayName: Test-Frontend
    jobs:
      - job: django_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[FRONTEND TEST]"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: $(Build.SourcesDirectory)/frontend/yarn.lock
              path: $(Build.SourcesDirectory)/frontend/node_modules
            displayName: Cache Yarn packages
          - script: yarn
            displayName: "Yarn Install"
            workingDirectory: 'frontend'

          - script: yarn test --watchAll=false
            workingDirectory: 'frontend'
            displayName: "Test"

  - stage: lint
    dependsOn: []
    displayName: Lint
    jobs:
      - job: flake8
        pool:
          vmImage: ubuntu-latest
        displayName: "[FLAKE8]"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.9.12"
            displayName: "Install Python"
          - script: |
              curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
              export PATH=$PATH:$HOME/.poetry/bin
              poetry install --no-root
            workingDirectory: 'backend'
            displayName: 'Install dependencies'
          - script: |
              mkdir -p ./lint-output
              export PATH=$PATH:$HOME/.poetry/bin
              poetry run flake8 --format=junit-xml . > ./lint-output/flake8.xml
            workingDirectory: 'backend'
            displayName: 'Run linter'

          - task: PublishTestResults@2
            displayName: "Publish lint Result"
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '*.xml'
              searchFolder: 'backend/lint-output/'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'Lint results'


  - stage: build_and_push
    dependsOn: lint
    displayName: BUILD and PUSH
    jobs:
      - job: build_push_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "[Build]"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registry)'
              command: 'login'
          - script: "docker pull $(Docker.url)/$(Docker.backend.repository):$(System.PullRequest.PullRequestId)-latest"
            displayName: Pull latest for layer caching for this branch
            continueOnError: true # for first build, no cache
          - script: "docker pull $(Docker.url)/$(Docker.backend.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              arguments: "--cache-from=$(Docker.url)/$(Docker.backend.repository):$(System.PullRequest.PullRequestId)-latest 
                          --cache-from=$(Docker.url)/$(Docker.backend.repository):latest"
              dockerfile: $(Docker.backend.filePath)
              repository: $(Docker.backend.repository)
              containerRegistry: $(Docker.registry)
              tags: |
                $(Build.BuildId)
                dev-latest
                $(System.PullRequest.PullRequestId)-latest
          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              dockerfile: $(Docker.backend.filePath)
              repository: $(Docker.backend.repository)
              containerRegistry: $(Docker.registry)
              tags: |
                $(Build.BuildId)
                dev-latest
                $(System.PullRequest.PullRequestId)-latest

  - stage: test_backend
    dependsOn: build_and_push
    displayName: Test-Backend
    jobs:
      - job: django_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[DJANGO TEST]"
        variables:
          backend_image: $(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)
        steps:
          - task: Docker@2
            displayName: "[ACR] Login"
            inputs:
              command: login
              containerRegistry: $(Docker.registry)
          - task: DownloadSecureFile@1
            inputs:
              secureFile: '.env-django-test'
          - task: CmdLine@2
            displayName: "Setup .env and docker-compose.tst.yml"
            inputs:
              script: |
               mv deployment/docker-compose.tst.yml docker-compose.tst.yml
               mv $(Agent.TempDirectory)/.env-django-test .env

          - task: DockerCompose@0
            displayName: "Run tests"
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureContainerRegistry: $(Docker.registry)
              dockerComposeFile: '**/docker-compose.tst.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'run backend ./docker-test-entrypoint.sh'
              dockerComposeFileArgs: |
               backend_image=$(Docker.url)/$(Docker.backend.repository):$(Build.BuildId)

          - task: PublishTestResults@2
            displayName: "Publish Test Result"
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '*.xml'
              searchFolder: 'backend/test-results/'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'TEST Results'

