trigger: none
pr: none
resources:
  repositories:
  - repository: hct-mis-helm
    type: github
    endpoint: "unicef (2)"
    name: unicef/hct-mis-helm

variables:
  # ========================================================================
  #                          Mandatory variables
  # ========================================================================
  Kubernetes.serviceConnection: "ICTD-HOPE-TRN-uni-apps-aks-hope-dev-ictd-hope-trn-1616938354772"
  Kubernetes.namespace: "ictd-hope-trn"
  Chart.version: "0.1.6"

stages:
  - stage: deploy
    displayName: DEPLOY
    jobs:
      - job: deploy_hope
        displayName: "[KOBO] Deployment"
        steps:
          - checkout: hct-mis-helm
          - task: HelmDeploy@0
            displayName: "DEPLOY"
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceConnection: $(Kubernetes.serviceConnection)
              namespace: $(Kubernetes.namespace)
              command: "upgrade"
              chartType: "FilePath"
              chartPath: 'pkg/kobo-$(Chart.version).tgz'
              releaseName: "kobo"
              install: true
              waitForExecution: false
              failOnStderr: false
              arguments: "--timeout 600s"
              overrideValues: "
                global.storageClass=default,\
                mongodb.mongodbPassword=$(MONGO_PASSWORD),\
                postgresql.postgresqlPassword=$(POSTGRES_PASSWORD),\
                rediscache.password=$(REDIS_CACHE_PASSWORD),\
                redismain.password=$(REDIS_MAIN_PASSWORD),\
                kobocat.ravenDsn=$(KOBOCAT_SENTRY_DSN),\
                kobocat.subdomain=kc-hope,\
                kobocat.resources.requests.cpu=250m,\
                kobotoolbox.superuserPassword=$(KOBO_SUPERUSER_PASSWORD),\
                smtp.email=kobo@unitst.org,\
                smtp.host=$(SMTP_HOST),\
                ingress.host=$(DOMAIN),\
                kpi.ravenDsn=$(KPI_SENTRY_DSN),\
                kpi.subdomain=kf-hope,\
                kpi.resources.requests.cpu=250m,\
                kpi.microsoftTenant=$(MICROSOFT_TENANT),\
                enketo.subdomain=ek-hope,\
                ingress.annotations.appgw\\.ingress\\.kubernetes\\.io/appgw-ssl-certificate=kv-cert-unitst,\
                ingress.scheme=https"
