trigger:
  batch: true
  branches:
    include:
    - develop
    - staging
    - master
    - global-program-filter
    - testing-ephemeral
    - ops/*
    - cicd-tests
  paths:
    exclude:
    -  docs/*
pr: none
resources:
  - repo: self

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Docker.backend.repository: "hope-backend"
  Docker.frontend.repository: "hope-frontend"
  Docker.registryConnection.trn: "ICTD-HOPE-DEV-ACR"
  Docker.url.trn: "uniappsakshopedev.azurecr.io"
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    Docker.registryConnection: "ICTD-HOPE-DEV-ACR"
    Docker.url: "uniappsakshopedev.azurecr.io"
    sentryEnvironment: "dev"
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    Docker.registryConnection: "ICTD-HOPE-PRD-ACR"
    Docker.url: "uniappsakshope.azurecr.io"
    sentryEnvironment: "production"
  isTraining: $[eq(variables['Build.SourceBranchName'], 'master')]
  isStaging: $[eq(variables['Build.SourceBranchName'], 'staging')]
  isEphemeral: $[eq(variables['Build.SourceBranchName'], 'global-program-filter')]
  isDev: $[eq(variables['Build.SourceBranchName'], 'develop')]
  tag: $(Build.SourceVersion)
  additionalTag: $(Build.SourceBranchName)

stages:
  - stage: test_frontend
    condition: false
    displayName: Test-Frontend
    jobs:
      - job: django_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[FRONTEND TEST]"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: $(Build.SourcesDirectory)/frontend/yarn.lock
              path: $(Build.SourcesDirectory)/frontend/node_modules
            displayName: Cache Yarn packages
          - script: yarn install --frozen-lockfile
            displayName: "Yarn Install"
            workingDirectory: 'frontend'
          - script: yarn test --watchAll=false
            workingDirectory: 'frontend'
            displayName: "Test"

  - stage: build_and_push_backend
    condition: false
    dependsOn: []
    displayName: BUILD and PUSH
    jobs:
      - job: build_push_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "[BACKEND_BUILD]"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registryConnection)'
              command: 'login'
          - task: Docker@2
            condition: and(succeeded(), eq(variables.isTraining, true))
            inputs:
              containerRegistry: '$(Docker.registryConnection.trn)'
              command: 'login'
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.backend.repository)-cache:$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.backend.repository)-cache:latest \
              --cache-to=$(Docker.url)/$(Docker.backend.repository)-cache:$(additionalTag) \
              --cache-to=$(Docker.url)/$(Docker.backend.repository)-cache:latest \
              -t $(Docker.url)/$(Docker.backend.repository):$(tag) \
              -t $(Docker.url)/$(Docker.backend.repository):latest \
              --push \
              ./backend
            displayName: Docker build
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.backend.repository)-cache:dev-$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.backend.repository)-cache:dev-latest \
              --cache-to=$(Docker.url)/$(Docker.backend.repository)-cache:dev-$(additionalTag) \
              --cache-to=$(Docker.url)/$(Docker.backend.repository)-cache:dev-latest \
              -t $(Docker.url)/$(Docker.backend.repository):dev-$(tag) \
              --push \
              --target dev \
              ./backend
            displayName: Docker build dev
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.backend.repository)-cache:$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.backend.repository)-cache:latest \
              --cache-to=$(Docker.url)/$(Docker.backend.repository)-cache:$(additionalTag) \
              -t $(Docker.url.trn)/$(Docker.backend.repository):$(tag) \
              --push \
              ./backend
            displayName: Docker build trn
            condition: and(succeeded(), eq(variables.isTraining, true))

  - stage: build_and_push_frontend
    condition: false
    dependsOn: []
    displayName: BUILD and PUSH frontend
    jobs:
      - job: build_and_push
        pool:
          vmImage: ubuntu-latest
        displayName: "[FRONTEND_BUILD]"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registryConnection)'
              command: 'login'
          - task: Docker@2
            condition: and(succeeded(), eq(variables.isTraining, true))
            inputs:
              containerRegistry: '$(Docker.registryConnection.trn)'
              command: 'login'
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:latest \
              --cache-to=$(Docker.url)/$(Docker.frontend.repository)-cache:$(additionalTag) \
              --cache-to=$(Docker.url)/$(Docker.frontend.repository)-cache:latest \
              -t $(Docker.url)/$(Docker.frontend.repository):$(tag) \
              -t $(Docker.url)/$(Docker.frontend.repository):latest \
              --build-arg SENTRY_DSN=$(SENTRY_DSN) \
              --build-arg SENTRY_ENVIRONMENT=$(sentryEnvironment) \
              --push \
              ./frontend
            displayName: Docker build dev
            condition: and(succeeded(), eq(variables.isDev, true))
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:latest \
              --cache-to=$(Docker.url)/$(Docker.frontend.repository)-cache:$(additionalTag) \
              --cache-to=$(Docker.url)/$(Docker.frontend.repository)-cache:latest \
              -t $(Docker.url)/$(Docker.frontend.repository):$(tag) \
              -t $(Docker.url)/$(Docker.frontend.repository):latest \
              --build-arg SENTRY_DSN=$(SENTRY_DSN) \
              --build-arg SENTRY_ENVIRONMENT=staging \
              --push \
              ./frontend
            displayName: Docker build staging
            condition: and(succeeded(), eq(variables.isStaging, true))
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:latest \
              -t $(Docker.url)/$(Docker.frontend.repository):$(tag) \
              -t $(Docker.url)/$(Docker.frontend.repository):latest \
              --build-arg SENTRY_DSN=$(SENTRY_DSN) \
              --build-arg SENTRY_ENVIRONMENT=ephemeral \
              --push \
              ./frontend
            displayName: Docker build ephemeral
            condition: and(succeeded(), eq(variables.isEphemeral, true))
          - script: |
              docker buildx create --use
              docker buildx build \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:$(additionalTag) \
              --cache-from=$(Docker.url)/$(Docker.frontend.repository)-cache:latest \
              -t $(Docker.url.trn)/$(Docker.frontend.repository):$(tag) \
              -t $(Docker.url.trn)/$(Docker.frontend.repository):latest \
              --build-arg SENTRY_DSN=$(SENTRY_DSN) \
              --build-arg SENTRY_ENVIRONMENT=training \
              --push \
              ./frontend
            displayName: Docker build trn
            condition: and(succeeded(), eq(variables.isTraining, true))

  - stage: test
    condition: false
    displayName: TEST
    dependsOn: build_and_push_backend
    jobs:
      - job: django_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[DJANGO TEST]"
        steps:
          - task: Docker@2
            displayName: "[ACR] Login"
            inputs:
              command: login
              containerRegistry: $(Docker.registryConnection)
          - task: DockerCompose@0
            displayName: "Run tests"
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureContainerRegistry: $(Docker.registryConnection)
              dockerComposeFile: '**/docker-compose.tst.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'run backend test'
              dockerComposeFileArgs: |
                backend_image=$(Docker.url)/$(Docker.backend.repository):dev-$(tag)
          - task: PublishTestResults@2
            displayName: "Publish Test Result"
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '*.xml'
              searchFolder: 'backend/test-results/'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'TEST Results'
          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: 'backend/coverage.xml'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: backend/coverage.xml
              artifact: BackendLineCoverage
              publishLocation: 'pipeline'

  - stage: publish_artifacts
    displayName: PUBLISH_ARTIFACTS
    dependsOn: [test]
    jobs:
      - job: publish_artifacts
        pool:
          vmImage: ubuntu-latest
        displayName: "[PUBLISH_ARTIFACTS]"
        steps:
          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)/tag
              echo $(tag) > $(Build.ArtifactStagingDirectory)/tag/hope.txt
            displayName: "Save tag to file"
          - task: PublishPipelineArtifact@1
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)/tag"
              artifact: 'hope'
              publishLocation: 'pipeline'
            displayName: "Publish tag"