trigger:
  batch: true
  branches:
    include:
    - develop
    - ops/*
  paths:
    exclude:
    -  docs/*
pr: none
resources:
  - repo: self

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Docker.backend.filePath: "**/backend/Dockerfile"
  Docker.frontend.filePath: "**/frontend/Dockerfile"
  Docker.backend.repository: "hope-backend"
  Docker.frontend.repository: "hope-frontend"
  Docker.registry: "ICTD-HOPE-DEV-ACR"
  Docker.repository: "uniappsk8shopedev" 
stages:
  - stage: build_and_push
    displayName: BUILD and PUSH
    jobs:
      - job: build_push_backend
        displayName: "[BACKEND]"
        steps:
          - task: Docker@2
            displayName: Build&Push
            inputs:
              command: buildAndPush
              dockerfile: $(Docker.backend.filePath)
              repository: $(Docker.repository)/$(Docker.backend.repository)
              containerRegistry: $(Docker.repository)
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                dev-latest

      - job: build_push_frontend
        displayName: "[FRONTEND]"
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              dockerfile: $(Docker.frontend.filePath)
              repository: $(Docker.repository)/$(Docker.frontend.repository)
              arguments: --build-arg SENTRY_FRONTEND_DSN=$(SENTRY_FRONTEND_DSN)
              containerRegistry: $(Docker.registry)
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                dev-latest
          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              dockerfile: $(Docker.frontend.filePath)
              repository: $(Docker.frontend.repository)
              containerRegistry: $(Docker.registry)
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                dev-latest

  - stage: test
    displayName: TEST
    jobs:
      - job: django_tests
        displayName: "[DJANGO TEST]"
        variables:
          backend_image: uniappsk8sdevacr.azurecr.io/$(Docker.backend.repository):$(Build.BuildId)
        steps:
          - task: Docker@2
            displayName: "[ACR] Login"
            inputs:
              command: login
              containerRegistry: $(Docker.registry)
          - task: DownloadSecureFile@1
            inputs:
              secureFile: '.env-django-test'
          - task: CmdLine@2
            displayName: "Setup .env and docker-compose.tst.yml"
            inputs:
              script: |
               mv deployment/docker-compose.tst.yml docker-compose.tst.yml
               mv $(Agent.TempDirectory)/.env-django-test .env

          - task: DockerCompose@0
            displayName: "Run tests"
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureContainerRegistry: $(Docker.registry)
              dockerComposeFile: '**/docker-compose.tst.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'run backend ./docker-test-entrypoint.sh'
              dockerComposeFileArgs: |
               backend_image=uniappsk8sdevacr.azurecr.io/$(Docker.backend.repository):$(Build.BuildId)

          - task: PublishTestResults@2
            displayName: "Publish Test Result"
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '*.xml'
              searchFolder: 'backend/test-results/'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'TEST Results'
