trigger: none
pr: none
resources:
  repositories:
  - repository: hct-mis-helm
    type: github
    endpoint: "unicef (2)"
    name: unicef/hct-mis-helm
  pipelines:
  - pipeline: ci-hope
    source: '[CI] HOPE'
    trigger: 
      branches:
      - master

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Kubernetes.serviceConnection: "ICTD-HOPE-TRN-uni-apps-aks-hope-dev-ictd-hope-trn-1616938354772"
  Kubernetes.namespace: "ictd-hope-trn"
  Docker.backend.repository: "hope-backend"
  Docker.frontend.repository: "hope-frontend"
  Docker.registry: "uniappsakshopedev.azurecr.io"
  Chart.version: "0.1.3"

stages:
  - stage: deploy
    displayName: DEPLOY
    jobs:
      - job: deploy_hope
        pool:
          vmImage: 'ubuntu-latest'
        displayName: "[HOPE] Deployment"
        steps:
          - checkout: self
          - checkout: hct-mis-helm
<<<<<<< HEAD
=======
          - task: HelmDeploy@0
            displayName: "Update Chart dependencies"
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: $(Kubernetes.serviceConnection)     
              command: package
              updatedependency: true
              chartPath: 'hct-mis-helm'
>>>>>>> TestingCypress2
          - task: HelmDeploy@0
            displayName: "DEPLOY"
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: $(Kubernetes.serviceConnection)
              namespace: $(Kubernetes.namespace)
              command: 'upgrade'
              chartType: 'FilePath'
<<<<<<< HEAD
              chartPath: 'hct-mis-helm/pkg/hope-$(Chart.version).tgz'
=======
              chartPath: 'hct-mis-helm'
>>>>>>> TestingCypress2
              releaseName: 'hope'
              install: true
              waitForExecution: false
              failOnStderr: false
              valueFile: 'hct-mis/deployment/pipeline-cd-trn.values.yaml'
              arguments: "--timeout 600s"
              overrideValues: "
                backend.image=$(Docker.registry)/$(Docker.backend.repository):$(Build.SourceVersion),\
                celery.image=$(Docker.registry)/$(Docker.backend.repository):$(Build.SourceVersion),\
                frontend.image=$(Docker.registry)/$(Docker.frontend.repository):$(Build.SourceVersion),\
                backend.secret.AZURE_CLIENT_ID=$(AZURE_CLIENT_ID),\
                backend.secret.SECRET_KEY=$(SECRET_KEY),\
                backend.secret.STORAGE_AZURE_ACCOUNT_KEY=$(STORAGE_AZURE_ACCOUNT_KEY),\
                backend.secret.AZURE_CLIENT_SECRET=$(AZURE_CLIENT_SECRET),\
                backend.secret.AZURE_TENANT_KEY=$(AZURE_TENANT_KEY),\
                backend.secret.SENTRY_DSN=$(SENTRY_DSN),\
                backend.secret.ROOT_ACCESS_TOKEN=$(ROOT_ACCESS_TOKEN),\
                backend.secret.EXCHANGE_RATES_API_KEY=$(EXCHANGE_RATES_API_KEY),\
                backend.secret.KOBO_APP_API_TOKEN=$(KOBO_APP_API_TOKEN),\
                postgresql.password=$(POSTGRES_PASSWORD),\
                registrationdatahubpostgresql.password=$(REGISTRATION_DATAHUB_POSTGRES_PASSWORD),\
                cashassistdatahubpostgresql.password=$(CASH_ASSIST_DATAHUB_POSTGRES_PASSWORD),\
                celeryflower.secret.FLOWER_BASIC_AUTH=$(FLOWER_BASIC_AUTH)"
