trigger: none
pr: none
resources:
  repositories:
  - repository: hct-mis-helm
    type: github
    endpoint: "unicef (2)"
    name: unicef/hct-mis-helm

variables:
  # ========================================================================
  #                          Mandatory variables
  # ========================================================================
  Kubernetes.serviceConnection: "ICTD-HOPE-PRD-uni-apps-aks-hope-prd-ictd-kobo-prd-1617968835008"
  Kubernetes.namespace: "ictd-kobo-prd"
  Chart.version: "0.1.1"

stages:
  - stage: deploy
    displayName: DEPLOY
    jobs:
      - job: deploy_hope
        displayName: "[KOBO] Deployment"
        steps:
          - checkout: hct-mis-helm
          - task: HelmDeploy@0
            displayName: "DEPLOY"
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceConnection: $(Kubernetes.serviceConnection)
              namespace: $(Kubernetes.namespace)
              command: "upgrade"
              chartType: "FilePath"
              chartPath: 'pkg/kobo-$(Chart.version).tgz'
              releaseName: "kobo"
              install: true
              waitForExecution: false
              failOnStderr: false
              arguments: "--timeout 600s"
              overrideValues: "
                global.storageClass=default,\
                mongodb.mongodbPassword=$(MONGO_PASSWORD),\
                kobotoolbox.superuserPassword=$(KOBO_SUPERUSER_PASSWORD),\
                kobocat.subdomain=kc-hope,\
                kobocat.resources.requests.cpu=250m,\
                kobocat.ravenDsn=$(KOBOCAT_SENTRY_DSN),\
                kpi.ravenDsn=$(KPI_SENTRY_DSN),\
                postgresql.postgresqlPassword=$(POSTGRES_PASSWORD),\
                rediscache.password=$(REDIS_CACHE_PASSWORD),\
                redismain.password=$(REDIS_MAIN_PASSWORD),\
                smtp.host=$(SMTP_HOST),\
                smtp.email=kobo@unitst.org,\
                ingress.host=$(DOMAIN),\
                ingress.scheme=https,\
                ingress.tls=true,\
                ingress.annotations.appgw\\.ingress\\.kubernetes\\.io/appgw-ssl-certificate=kv-cert-hope"
