trigger:
  paths:
    include:
      - frontend/*
pr:
  - master
  - develop
resources:
  - repo: self

stages:
  - stage: test_frontend
    displayName: Test-Frontend
    jobs:
      - job: django_tests
        pool:
          vmImage: ubuntu-latest
        displayName: "[FRONTEND TEST]"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: $(Build.SourcesDirectory)/frontend/yarn.lock
              path: $(Build.SourcesDirectory)/frontend/node_modules
            displayName: Cache Yarn packages
          - script: yarn
            displayName: "Yarn Install"
            workingDirectory: 'frontend'

          - script: yarn test --watchAll=false
            workingDirectory: 'frontend'
            displayName: "Test"
