name: 'Setup Docker Environment'
description: 'Sets up Docker environment variables and logs into DockerHub'
inputs:
  dockerhub_organization:
    description: 'DockerHub organization'
    required: false
    default: 'unicef'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker environment
      run: |
        echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
        echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
        echo "DOCKERHUB_ORGANIZATION=${{ inputs.dockerhub_organization }}" >> $GITHUB_ENV

    - name: DockerHub login
      uses: docker/login-action@v1
      if: ${{ env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}