version: '3.7'

services:

  backend:
    image: ${backend_image}
    volumes:
      - ../../src/test-coverage:/code/backend/test-coverage
      - ./dev.sh:/code/dev.sh
    depends_on:
      - db
      - redis
      - elasticsearch
    profiles:
      - unit
      - selenium
    env_file:
      - .env

  init_fe:
    image: ${dist_backend_image}
    volumes:
      - backend-web-app:/tmp/
    command: |
      sh -c "
        cp -r ./hct_mis_api/apps/web/* /tmp/
      "
    restart: "no"
    profiles:
      - selenium

  celery_worker:
    image: ${backend_image}
    restart: unless-stopped
    command: "celery -A hct_mis_api.apps.core.celery worker -E -l info"
    depends_on:
      - backend
      - db
      - redis
      - elasticsearch
    profiles:
      - selenium
    env_file:
      - .env

  db:
    image: kartoza/postgis:14-3
    volumes:
      - ../../development_tools/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=unicef_hct_mis_cashassist,rdi_datahub,mis_datahub,erp_datahub,ca_datahub
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_SSL_MODE=off
    ports:
      - "5433:5432"
    profiles:
      - unit
      - selenium

  redis:
    restart: unless-stopped
    image: redis:4.0.11-alpine3.8
    profiles:
      - unit
      - selenium

  elasticsearch:
    image: unicef/hct-elasticsearch
    build:
      context: ../../development_tools/elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    profiles:
      - unit
      - selenium
