revision: 1
namespace: staging
env: 

backend:
  image:
  maxUnavilable: 0
  maxSurge: 1
  replicas: 1
  port: 8000
  secret:
    SECRET_KEY: ""
    POSTGRES_DB: ""
    POSTGRES_USER: ""
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST: ""
    DJANGO_ALLOWED_HOST: ""
    DOMAIN: ""
    ENV: ""
  staticStorage:
    secretName: ""
    accountName: ""

frontend:
  image:
  maxUnavilable: 0
  maxSurge: 1
  replicas: 1
  port: 80

redis:
  image: redis
  port: 6379


postgres:
  port: 5432
  image: postgres:9.5.15-alpine
  secret:
    POSTGRES_DB: ""
    POSTGRES_USER: ""
    POSTGRES_PASSWORD: ""
