revision: 1
namespace: staging
env:

backend:
  image:
  maxUnavilable: 0
  maxSurge: 1
  replicas: 1
  port: 8000
  secret:
    SECRET_KEY: ""
    POSTGRES_DB: ""
    POSTGRES_USER: ""
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST: ""
    POSTGRES_CASHASSIST_DATAHUB_DB: ""
    POSTGRES_CASHASSIST_DATAHUB_USER: ""
    POSTGRES_CASHASSIST_DATAHUB_PASSWORD: ""
    POSTGRES_CASHASSIST_DATAHUB_HOST: ""
    POSTGRES_REGISTRATION_DATAHUB_DB: ""
    POSTGRES_REGISTRATION_DATAHUB_USER: ""
    POSTGRES_REGISTRATION_DATAHUB_PASSWORD: ""
    POSTGRES_REGISTRATION_DATAHUB_HOST: ""
    DJANGO_ALLOWED_HOST: ""
    DOMAIN: ""
    ENV: ""
  staticStorage:
    secretName: ""
    accountName: ""

frontend:
  image:
  maxUnavilable: 0
  maxSurge: 1
  replicas: 1
  port: 80

redis:
  image: redis
  port: 6379


postgres:
  port: 5432
  image: postgres:9.5.15-alpine
  instances:
    postgres_cash_assist_datahub_db:
      secret:
        POSTGRES_DB: ""
        POSTGRES_USER: ""
        POSTGRES_PASSWORD: ""
    postgres_registration_datahub:
        secret:
          POSTGRES_DB: ""
          POSTGRES_USER: ""
          POSTGRES_PASSWORD: ""
    postgres:
        secret:
          POSTGRES_DB: ""
          POSTGRES_USER: ""
          POSTGRES_PASSWORD: ""

