global:
  env: dev
  storageClass: default

backend:
  image: uniappsakshopedev.azurecr.io/hope-backend:07155fb3cbbd118d9d2044de851bba75d2c12e5f
  replicaCount: 1
  initCommand: "python3 /code/manage.py initdemo"
  secret:
    AZURE_CLIENT_ID: 06e50a84-27be-4910-b2ea-43381976c79a
    AZURE_CLIENT_SECRET: CR.zoNYWhK-7pUihJdSsJw1U6/WuxV=3
    AZURE_TENANT_KEY: 77410195-14e1-4fb8-904b-ab1892023667
    STORAGE_AZURE_ACCOUNT_NAME: hctmisdev-gf
    STORAGE_AZURE_ACCOUNT_KEY: "wo7xPqwh7uxMqWMBwKZgGEVA/AdUDSxrrK/HXFzdmlb+J91xahO23eBeo3SUJn+zmckcWlw6ECHq6czENUNnpw=="
    SECRET_KEY: 219057ofhasjfhaklsfhaor8*
    SENTRY_DNS: "https://88d65a39ff5d42a9bff63f6b0eff4c19@excubo.unicef.io/43"
    EMAIL_HOST: extmail01.unicef.org
    EMAIL_USE_TLS: "false"
    EXCHANGE_RATES_API_KEY: 743bb5f5b5004c89b4809b0679ecf20d
    ROOT_ACCESS_TOKEN: 3ad5b22b-9bb0-4d6e-bb66-abfb3547aa2e

frontend:
  image: uniappsakshopedev.azurecr.io/hope-frontend:07155fb3cbbd118d9d2044de851bba75d2c12e5f

celery:
  image: uniappsakshopedev.azurecr.io/hope-backend:07155fb3cbbd118d9d2044de851bba75d2c12e5f
  replicaCount: 1

celeryflower:
  secret:
    FLOWER_BASIC_AUTH: hope-gf

ingress:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  host: gf-hope-dev.unitst.org
  tls: "true"

#
# Defaults for postgres databases, applies to ephemerals only
#
psql-auth-default: &psql-auth-default
  username: hope-gf
  password: hope-gf

psql-image-default: &psql-image-default
  image:
    repository: postgis/postgis
    tag: 10-3.2

psql-resources-default: &psql-resources-default
  resources:
    requests:
      cpu: 0.2
      memory: 100M
    limits:
      cpu: 1
      memory: 1.5G
#
# Databases
#
postgresql:
  enabled: true
  <<: *psql-image-default
  auth:
    database: hope-gf
    <<: *psql-auth-default
  persistence:
    enabled: false
  <<: *psql-resources-default

registrationdatahubpostgresql:
  enabled: true
  <<: *psql-image-default
  auth:
    database: registrationdatahubpostgresql
    <<: *psql-auth-default
  persistence:
    enabled: false
  <<: *psql-resources-default

cashassistdatahubpostgresql:
  <<: *psql-image-default
  enabled: true
  auth:
    database: cashassistdatahubpostgresql
    <<: *psql-auth-default
  initScripts:
      create_cashassist-schemas.sh: |
        psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" - <<-EOSQL
        CREATE EXTENSION IF NOT EXISTS POSTGIS;
        CREATE SCHEMA IF NOT EXISTS mis;
        CREATE SCHEMA IF NOT EXISTS erp;
        CREATE SCHEMA IF NOT EXISTS ca;
        EOSQL
  persistence:
    enabled: false
  <<: *psql-resources-default


redis:
  enabled: true
  fullnameOverride: hope-main-redis
  persistence.enabled: true
  usePassword: false
  redis:
    usePassword: false
  cluster:
    slaveCount: 0
    enabled: false
  image:
    tag: 4.0.14

elasticsearch:
  enabled: true
  data:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 0.4
  master:
    replicas: 1
  sysctlImage:
    replicas: 1
  plugins: "analysis-phonetic"
  externalElasticsearch:
    host: ""

