---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hct-mis
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    
spec:
  rules:
    - host: tivix-dev.unitst.org
      http:
        paths:
        - path: /
          backend:
            serviceName: backend
            servicePort: 8000
---
