---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-migrations
  annotations:
    revision: "{{ .Values.revision }}"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    redeploy: "true"
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - name: job-migrations-container
        image: {{ .Values.backend.image }}
        command: ["/bin/sh"]
        args: ["-c", "python3 /code/manage.py migratealldb"]
        envFrom:
          - secretRef:
              name: backend-secret
        env:
          - name: STORAGE_AZURE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.staticStorage.secretName }}
                key: password
          - name: STORAGE_AZURE_ACCOUNT_NAME
            value: {{ .Values.backend.staticStorage.accountName }}
      restartPolicy: Never
  backoffLimit: 20
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-static
  annotations:
    revision: "{{ .Values.revision }}"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    redeploy: "true"
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - name: job-static-container
        image: {{ .Values.backend.image }}
        command: ["/bin/sh"]
        args: ["-c", "python3 /code/manage.py collectstatic --noinput"]
        env:
          - name: STORAGE_AZURE_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.staticStorage.secretName }}
                key: password
          - name: STORAGE_AZURE_ACCOUNT_NAME
            value: {{ .Values.backend.staticStorage.accountName }}
        envFrom:
          - secretRef:
              name: backend-secret
      restartPolicy: Never
  backoffLimit: 20
---
