---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-migrations
  annotations:
    revision: "{{ .Values.revision }}"
  labels:
    redeploy: "true"
  namespace: {{ .Values.namespace }}
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  template:
    spec:
      containers:
      - name: job-migrations-container
        image: {{ .Values.backend.image }}
        command: ["/bin/sh"]
        args: ["-c", "python3 /code/manage.py migrate --noinput"]
        envFrom:
          - secretRef:
              name: backend-secret
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-static
  annotations:
    revision: "{{ .Values.revision }}"
  labels:
    redeploy: "true"
  namespace: {{ .Values.namespace }}
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  template:
    spec:
      containers:
      - name: job-static-container
        image: {{ .Values.backend.image }}
        command: ["/bin/sh"]
        args: ["-c", "python3 /code/manage.py collectstatic --noinput && python3 /code/manage.py compress"]
        envFrom:
          - secretRef:
              name: backend-secret
      restartPolicy: Never
  backoffLimit: 4
---