---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace:  {{ .Values.namespace }}
data:
  {{- range $key, $value :=  .Values.backend.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- range $name, $postgres :=  .Values.postgres.instances }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace:  {{ $.Values.namespace }}
data:
  {{- range $key, $value :=  $postgres.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}