---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: "Local"
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
  type: LoadBalancer
  selector:
      app: backend
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: "Local"
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
  type: LoadBalancer
  selector:
    app: frontend
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
  selector:
    app: redis
--- 
# {{- range $key, $value :=  .Values.databases }}
# kind: Service
# apiVersion: v1
# metadata:
#   name: {{ $key }}
#   namespace: {{ $.Values.namespace }}
# spec:
#   ports:
#     - protocol: TCP
#       port: {{ $value.port }}
#   selector:
#     app: {{ $key }}
# ---
# {{- end }}
