---
kind: Service
apiVersion: v1
metadata:
  name: backend
  annotations:
    revision: {{ .Values.revision }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    protocol: TCP
    port: {{ .Values.backend.port }}
  selector:
      app: backend
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  annotations:
    revision: {{ .Values.revision }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    protocol: TCP
    port: {{ .Values.frontend.port }}
  selector:
    app: frontend
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  annotations:
    revision: {{ .Values.revision }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    protocol: TCP
    port: {{ .Values.redis.port }}
  selector:
    app: redis
--- 
kind: Service
apiVersion: v1
metadata:
  name: postgres
  annotations:
    revision: {{ .Values.revision }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    protocol: TCP
    port: {{ .Values.postgres.port }}
  selector:
    app: postgres
---
