trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    -  docs/*

resources:
  - repo: self

variables:
  frontendDockerFilePath: "**/frontend/Dockerfile"
  backendDockerFilePath: "**/backend/Dockerfile"

stages:
  - stage: Build
    displayName: Build and push images
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@0
            displayName: Build and push backend image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(backendDockerFilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              imageName: hct-mis-backend
              tags: |
                $(commitHash)
          - task: Docker@0
            displayName: Build and frontend image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(frontendDockerFilePath)
              imageName: hct-mis-frontend
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(commitHash)
