trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    -  docs/*

resources:
  - repo: self

variables:
  frontendDockerFilePath: "**/frontend/Dockerfile"
  backendDockerFilePath: "**/backend/Dockerfile"
  azureSubscription: "UNICEF_APP RS-UNI-APPS-K8S-DEV"
  dockerRegistryServiceConnection: '93d89218-5799-4277-8e6a-a1b268745904'
  containerRegistry: 'uniappsk8sdevacr.azurecr.io'

stages:
  - stage: Build
    displayName: Build and push images
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@0
            displayName: Build and push backend image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(backendDockerFilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              imageName: hct-mis-backend
              tags: |
                $(commitId)
          - task: Docker@0
            displayName: Build and push frontend image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(frontendDockerFilePath)
              imageName: hct-mis-frontend
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(commitId)
