trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    -  docs/*

resources:
  - repo: self

variables:
  frontendDockerFilePath: "**/frontend/Dockerfile"
  backendDockerFilePath: "**/backend/Dockerfile"
  kubernetesServiceConnection: 'ICTD-HCT-MIS-Demo-uni-apps-K8s-dev-hct-ims-dev-1574767480012'
  imageRepository: "hct-mis"
  containerRegistry: "uniappsk8sdevacr"

stages:
  - stage: Build
    displayName: Build and push images
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            displayName: Build and push backend image
            inputs:
              command: buildAndPush
              dockerfile: $(backendDockerFilePath)
              repository: $(imageRepository)
              containerRegistry: $(containerRegistry)
              imageName: backend
              tags: |
                $(Build.BuildId)

          - task: Docker@2
            displayName: Build and push frontend image
            inputs:
              command: buildAndPush
              dockerfile: $(frontendDockerFilePath)
              imageName: frontend
              repository: $(imageRepository)
              containerRegistry: $(containerRegistry)
              tags: |
                $(Build.BuildId)
