name: CI

on:
  push:
    branches:
    - gha

jobs:
  build_and_push_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build dev
        run: |
          docker buildx create --use
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-latest-dev \
            -f ./docker/Dockerfile \
            --target dev \
            --load \
            ./

      - name: Static checks
        run: |
          docker run --rm -i ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev sh -c "
            ./dev.sh sort
            ./dev.sh format
            ./dev.sh lint
            ./dev.sh mypy
          "

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push dev
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-latest-dev \
            -f ./docker/Dockerfile \
            --target dev \
            --push \
            ./

  build_and_push_dist:
    needs: [build_and_push_dev]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push dist
        run: |
          docker buildx create --use
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dist \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-latest-dist \
            -f ./docker/Dockerfile \
            --target dist \
            --push \
            ./

  unit_tests:
    runs-on: ubuntu-latest
    needs: [build_and_push_dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unit tests
        run: |
          backend_image=${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev \
          docker compose \
            -f ./deployment/docker-compose.tst.yml \
            up \
              --exit-code-from backend \
              --abort-on-container-exit

  e2e_tests:
    runs-on: ubuntu-latest
    needs: [build_and_push_dist, build_and_push_dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: E2E tests
        run: |
          dist_backend_image=${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dist \
          dev_backend_image=${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev \
          docker compose \
            -f ./deployment/docker-compose.tst.yml \
            up \
              --exit-code-from backend \
              --abort-on-container-exit

  trivy:
    runs-on: ubuntu-latest
    needs: [ build_and_push_dist]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trivy
        run: |
          docker run --rm -i aquasec/trivy:latest ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dist