name: CI

on:
  push:
    branches:
    - develop
    - staging
    - master
    - ephemeral-*
    - feat/short-run-only-on-pr
  pull_request:
    branches:
    - develop
    - staging
    - master
    - ephemeral-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Print if it's a PR or push
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "This is a PR"
          else
            echo "This is a push"
          fi
