name: CI

on:
  push:
    branches:
    - gha

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build dev
        run: |
          docker buildx create --use
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-latest-dev \
            -f ./docker/Dockerfile \
            --target dev \
            --load \
            ./

      - name: Checks
        run: |
          docker run --rm -i ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev sh -c "
            ./dev.sh sort
            ./dev.sh format
            ./dev.sh lint
            ./dev.sh mypy
          "

      - name: Push dev
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-${{ github.sha }}-dev \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hope:core-latest-dev \
            -f ./docker/Dockerfile \
            --target dev \
            --push \
            ./