name: Docker Setup

on: workflow_call

jobs:
  setup-docker-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker environment
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
          if [ -n "${{ vars.DOCKERHUB_ORGANIZATION }}" ]; then
            echo "DOCKERHUB_ORGANIZATION=${{ vars.DOCKERHUB_ORGANIZATION }}" >> $GITHUB_ENV
          else
            echo "DOCKERHUB_ORGANIZATION=unicef" >> $GITHUB_ENV
      - name: DockerHub login
        uses: docker/login-action@v1
        if: ${{ env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}