name: DockerHub Login

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      DOCKERHUB_TOKEN:
        required: true
        type: string
      DOCKERHUB_ORGANIZATION:
        required: false
        type: string
        default: unicef

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        run: |
          echo "DOCKERHUB_USERNAME=${{ inputs.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKERHUB_TOKEN=${{ inputs.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
          echo "DOCKERHUB_ORGANIZATION=${{ inputs.DOCKERHUB_ORGANIZATION }}" >> $GITHUB_ENV

      - name: DockerHub login
        uses: docker/login-action@v1
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ inputs.DOCKERHUB_TOKEN }}
